### ISSUE TITLE
Lack of `.json` extension prevents webpack from loading

### ISSUE THREAD

**Issue by brianium** [betit/known-css-properties#31]
Importing `./data/all` from `index.js` doesn't work with webpack. Tacking on `.json` allows this to work with webpack, and should still work in node envs.

**Comment by vio** [comment]
@brianium Can you please elaborate on your use case? My guess is that your [`resolve.extensions` is not containing `.json` anymore](https://webpack.js.org/configuration/resolve/#resolve-extensions).

While the statement is ok for node module resolving, I am aware that there are issues when used in other environments that are not having the same resolving behavior (eg: https://github.com/facebook/jest/issues/3252).

Adding the extension should avoid this issues, please feel free to create a PR ;)
